<a href="https://colab.research.google.com/github/KokiNiimura/study/blob/master/tutorial0102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is PyTorch?

In [20]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[5.8272e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.1446e-36]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0154, 0.0708, 0.2593],
        [0.8791, 0.3264, 0.3427],
        [0.0115, 0.1298, 0.1665],
        [0.8305, 0.9140, 0.7299],
        [0.6698, 0.1698, 0.6242]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.7956, 0.5869, 0.4060],
        [0.7663, 0.8575, 0.6872],
        [0.5838, 0.4471, 0.1625],
        [0.3513, 0.3097, 0.4023],
        [0.1926, 0.0418, 0.5476]])


In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.9949, 1.4400, 0.4701],
        [0.8059, 0.9862, 1.2291],
        [0.9278, 0.9076, 0.5379],
        [0.7849, 1.0150, 1.2648],
        [0.5897, 0.6177, 0.7990]])


In [8]:
print(torch.add(x, y))

tensor([[0.9949, 1.4400, 0.4701],
        [0.8059, 0.9862, 1.2291],
        [0.9278, 0.9076, 0.5379],
        [0.7849, 1.0150, 1.2648],
        [0.5897, 0.6177, 0.7990]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9949, 1.4400, 0.4701],
        [0.8059, 0.9862, 1.2291],
        [0.9278, 0.9076, 0.5379],
        [0.7849, 1.0150, 1.2648],
        [0.5897, 0.6177, 0.7990]])


In [10]:
y.add_(x)
print(y)

tensor([[0.9949, 1.4400, 0.4701],
        [0.8059, 0.9862, 1.2291],
        [0.9278, 0.9076, 0.5379],
        [0.7849, 1.0150, 1.2648],
        [0.5897, 0.6177, 0.7990]])


In [11]:
print(x[:, 1])

tensor([0.5869, 0.8575, 0.4471, 0.3097, 0.0418])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3580])
0.3579615354537964


In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.3580], device='cuda:0')
tensor([1.3580], dtype=torch.float64)


## Autograd

In [21]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [22]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [23]:
print(y.grad_fn)

In [24]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [25]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [26]:
out.backward()

In [27]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [29]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 514.4454, 1375.6422,  -67.1842], grad_fn=<MulBackward0>)


In [30]:
v =  torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [32]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
